"""Write docs/astra-robodawn-demos.md: every real Astra run with its video links, settings and result.

Regenerate after every run (no model or simulator is used):

    python3 scripts/robocasa-astra/demo_index.py

Source of truth: runs/astra_ledger.jsonl (one line per real run) plus each run directory
(config.json, summary.json, system_prompt.md, video files). Notes per run live in
docs/astra-robodawn-demo-notes.json ({"<run dir name>": "note"}) so they survive regeneration.
"""

import hashlib
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
LEDGER = REPO / "runs" / "astra_ledger.jsonl"
OUT = REPO / "docs" / "astra-robodawn-demos.md"
NOTES = REPO / "docs" / "astra-robodawn-demo-notes.json"
VIDEOS = (("debug_sim.mp4", "debug (sim time)"), ("debug_realtime.mp4", "debug (real time + prompt)"),
          ("video.mp4", "raw cameras"))


def _phase(name: str) -> str:
    return name.split("-", 1)[0] if name[:1] == "P" and name[1:2].isdigit() else "?"


def _link(run: Path, file: str) -> str:
    return f"[{file}](../runs/robodawn/{run.name}/{file})"


def main() -> None:
    notes = json.loads(NOTES.read_text()) if NOTES.exists() else {}
    rows, details = [], []
    for k, line in enumerate(LEDGER.read_text().splitlines(), start=1):
        entry = json.loads(line)
        run = Path(entry["run_dir"])
        config = json.loads((run / "config.json").read_text()) if (run / "config.json").exists() else {}
        summary = json.loads((run / "summary.json").read_text()) if (run / "summary.json").exists() else None
        prompt = run / "system_prompt.md"
        prompt_id = hashlib.md5(prompt.read_bytes()).hexdigest()[:8] if prompt.exists() else "-"
        scene = config.get("scene")
        scene_text = f"scene {scene} ({config['scene_info']['scene_id']})" if scene is not None else f"native seed {config.get('seed')}"
        if summary:
            result = f"{'SUCCESS' if summary['success'] else 'fail'} ({summary['finished_reason']})"
            steps = f"{summary['steps_used']}/{summary['step_budget']}"
            cost = summary["cost"]
            usage = summary["usage"]
            spend = f"{cost['credits']:.1f} cr / ${cost['usd_api_equivalent']:.2f}"
            minutes = f"{summary['wall_seconds'] / 60:.1f} min"
            turns = str(summary["turns"])
        else:
            result, steps, spend, minutes, usage = "interrupted (no summary)", "-", "-", "-", {}
            turns = str(len((run / "trace.jsonl").read_text().splitlines())) if (run / "trace.jsonl").exists() else "-"
        videos = " · ".join(_link(run, f) for f, _ in VIDEOS if (run / f).exists()) or "-"
        rows.append(f"| {k} | {_phase(run.name)} | {config.get('task', entry['task'])} | {scene_text} | "
                    f"{config.get('shots', entry['shots'])} | {result} | {turns} | {steps} | {spend} | {minutes} | {videos} |")
        demos = ", ".join(d["name"] for d in config.get("demos", [])) or "-"
        details += [
            f"### {k}. `{run.name}`", "",
            f"- Result: {result}; turns {turns}; native steps {steps}; wall time {minutes}",
            f"- Settings: task {config.get('task')}, {scene_text}, {config.get('shots')}-shot, step budget "
            f"{config.get('budget')}, max turns {config.get('max_turns')}, model {config.get('model')} "
            f"(effort {config.get('reasoning_effort')}), Codex {config.get('codex_version')}, git {str(config.get('git_commit'))[:7]}",
            f"- Prompt: system prompt md5 `{prompt_id}`; in-context demos: {demos}",
            f"- Tokens: input {usage.get('input_tokens', 0):,} (cached {usage.get('cached_input_tokens', 0):,}), "
            f"output {usage.get('output_tokens', 0):,}; spend {spend}",
            "- Videos: " + (" · ".join(f"{label}: {_link(run, f)}" for f, label in VIDEOS if (run / f).exists()) or "-"),
            f"- Run directory: `runs/robodawn/{run.name}` (trace.jsonl, calls/, turns/, replay/)",
        ]
        if notes.get(run.name):
            details.append(f"- Note: {notes[run.name]}")
        details.append("")
    text = [
        "# Astra × RoboCasa demos (astra_robodawn)", "",
        "Every real `gpt-6-astra` run, newest last, generated by `scripts/robocasa-astra/demo_index.py` from "
        "`runs/astra_ledger.jsonl` and the run directories. Links point into `runs/` (local, not in Git). "
        "Run notes are kept in `docs/astra-robodawn-demo-notes.json`. Background and reviews: "
        "`context_test_docs/` (progress.md, results.md).", "",
        "Phases: P4 = first run (OpenCabinet 0-shot); P6 = five tasks, 1-shot, layout 1/style 1 scenes without success "
        "conditions in the prompt; P7 = common scene 0, 1-shot, success conditions in the prompt; P8 = OpenCabinet "
        "scene 0 with a 3600-step budget (stopped at turn 17).", "",
        "| # | phase | task | scene | shots | result | turns | steps | credits / API $ | time | videos |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
        *rows, "", "## Run details", "", *details,
    ]
    OUT.write_text("\n".join(text))
    print(f"wrote {OUT} ({len(rows)} runs)")


if __name__ == "__main__":
    main()
